version: '3.8' # version は残しても削除してもOK

services:
  # フロントエンド
  frontend:
    container_name: gado-front
    build:
      context: .
      target: development-stage  # 開発用ステージを使用
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # ホストの8080をコンテナの8080にマッピング
    volumes:
      - .:/app          # ソースコードをマウント
      - /app/node_modules # node_modulesはマウント対象外 (コンテナ内のものを使う)
    environment:
      - NODE_ENV=development
      # VUE_APP_API_URLは、ブラウザからアクセスするURLなので localhost:8000 でOK
      - VUE_APP_API_URL=http://localhost:8000
    # depends_on: backend # 削除
    networks: # ネットワーク定義も削除（デフォルトネットワークで十分な場合が多い）
      - app-network # 削除しても良いかもしれないが、残す場合はnetworksセクションも残す

networks: # 上でfrontendのnetworksを削除した場合は、このセクションも削除
  app-network:
    driver: bridge

# volumes: db_data: # dbサービスを削除したので、これも削除